### ISSUE TITLE
Crimson planks has missing texture.

### ISSUE THREAD

**Issue by LimitlessCraft** [PixelAlphas/Devamped#7] opened 2023-10-19 14:28 UTC
Crimson planks texture has either been removed or placed in wrong folder destination.

**Comment by PixelAlphas** [comment] 2023-10-19 16:12
Looks like I deleted the old one and somehow messed up the packing process, will update it in next probably half of hour.

**Comment by PixelAlphas** [comment] 2023-11-09 21:08
Forgot to close this but the issue is resolved.

**Closed** 2023-11-09 21:08 UTC
